(function() {var implementors = {};
implementors["capsules"] = ["impl&lt;'a, A:&nbsp;<a class=\"trait\" href=\"kernel/hil/time/trait.Alarm.html\" title=\"trait kernel::hil::time::Alarm\">Alarm</a> + 'a&gt; <a class=\"trait\" href=\"kernel/hil/time/trait.Client.html\" title=\"trait kernel::hil::time::Client\">Client</a> for <a class=\"struct\" href=\"capsules/isl29035/struct.Isl29035.html\" title=\"struct capsules::isl29035::Isl29035\">Isl29035</a>&lt;'a, A&gt;","impl&lt;'a, A:&nbsp;<a class=\"trait\" href=\"kernel/hil/time/trait.Alarm.html\" title=\"trait kernel::hil::time::Alarm\">Alarm</a>&gt; <a class=\"trait\" href=\"kernel/hil/time/trait.Client.html\" title=\"trait kernel::hil::time::Client\">Client</a> for <a class=\"struct\" href=\"capsules/timer/struct.TimerDriver.html\" title=\"struct capsules::timer::TimerDriver\">TimerDriver</a>&lt;'a, A&gt;","impl&lt;'a, A:&nbsp;<a class=\"trait\" href=\"kernel/hil/time/trait.Alarm.html\" title=\"trait kernel::hil::time::Alarm\">Alarm</a> + 'a&gt; <a class=\"trait\" href=\"kernel/hil/time/trait.Client.html\" title=\"trait kernel::hil::time::Client\">Client</a> for <a class=\"struct\" href=\"capsules/sdcard/struct.SDCard.html\" title=\"struct capsules::sdcard::SDCard\">SDCard</a>&lt;'a, A&gt;","impl&lt;'a, A:&nbsp;<a class=\"trait\" href=\"kernel/hil/time/trait.Alarm.html\" title=\"trait kernel::hil::time::Alarm\">Alarm</a> + 'a&gt; <a class=\"trait\" href=\"kernel/hil/time/trait.Client.html\" title=\"trait kernel::hil::time::Client\">Client</a> for <a class=\"struct\" href=\"capsules/si7021/struct.SI7021.html\" title=\"struct capsules::si7021::SI7021\">SI7021</a>&lt;'a, A&gt;","impl&lt;'a, Alrm:&nbsp;<a class=\"trait\" href=\"kernel/hil/time/trait.Alarm.html\" title=\"trait kernel::hil::time::Alarm\">Alarm</a>&gt; <a class=\"trait\" href=\"kernel/hil/time/trait.Client.html\" title=\"trait kernel::hil::time::Client\">Client</a> for <a class=\"struct\" href=\"capsules/virtual_alarm/struct.VirtualMuxAlarm.html\" title=\"struct capsules::virtual_alarm::VirtualMuxAlarm\">VirtualMuxAlarm</a>&lt;'a, Alrm&gt;","impl&lt;'a, Alrm:&nbsp;<a class=\"trait\" href=\"kernel/hil/time/trait.Alarm.html\" title=\"trait kernel::hil::time::Alarm\">Alarm</a>&gt; <a class=\"trait\" href=\"kernel/hil/time/trait.Client.html\" title=\"trait kernel::hil::time::Client\">Client</a> for <a class=\"struct\" href=\"capsules/virtual_alarm/struct.MuxAlarm.html\" title=\"struct capsules::virtual_alarm::MuxAlarm\">MuxAlarm</a>&lt;'a, Alrm&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
